services:
  mongo:
    image: mongo:4.4.6-bionic
    container_name: mongodb
    env_file:
      - .env
    ports:
      - 127.0.0.1:${DC_MONGO_PORTS}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DC_MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DC_MONGO_PASS}
    networks:
      - mongodb-net

  mongo-express:
    image: mongo-express
    container_name: mongoadmin
    depends_on:
      - mongo
    env_file:
      - .env
    ports:
      - 127.0.0.1:${DC_MONGO_ADMIN_PORTS}
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DC_MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DC_MONGO_PASS}
      ME_CONFIG_BASICAUTH_USERNAME: ${DC_MONGO_ADMIN_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DC_MONGO_ADMIN_PASS}
    networks:
      - mongodb-net

  audio-chat-service:
    container_name: audio-chat-service
    build:
      context: ./
      dockerfile: Dockerfile.dev
    depends_on:
      - mongo
    ports:
      - 127.0.0.1:${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    networks:
      - mongodb-net

networks:
  mongodb-net:
    driver: bridge
