FROM node:16-buster

ENV MONGODB_URL=${MONGODB_URL}
ENV MONGODB_NAME=${MONGODB_NAME}

RUN mkdir -p /app
WORKDIR /app

COPY package.json .
COPY package-lock.json .

RUN npm ci

COPY . .

RUN npm run build

EXPOSE ${APP_PORT}

CMD ["npm", "run", "start:prod"]